version: '3'

services:

  client:
    image: client
    build:
      context: Client
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200

  WebAPI: 
    image: WebAPI
    build:
      context: WebAPI
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200